#!/usr/bin/env python3
"""Generate portable SwiftPM strings from the app's canonical String Catalog."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
catalog = json.loads((root / 'native/RelayCore/Resources/Localizable.xcstrings').read_text())
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for language in ('en', 'it'):
    lines = ['/* Generated by scripts/localization.py; edit Localizable.xcstrings. */']
    for key, entry in sorted(catalog['strings'].items()):
        unit = entry.get('localizations', {}).get(language, {}).get('stringUnit')
        if language != catalog['sourceLanguage'] and unit is None:
            raise SystemExit(f'Missing {language} translation: {key}')
        value = unit['value'] if unit else key
        lines.append(f'{json.dumps(key, ensure_ascii=False)} = {json.dumps(value, ensure_ascii=False)};')
    content = '\n'.join(lines) + '\n'
    path = root / f'native/RelayCore/PackageResources/{language}.lproj/Localizable.strings'
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Run python3 scripts/localization.py: {path.relative_to(root)} is stale')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
